### ISSUE TITLE
CORAZÓN FRENETICO MISIONES

### ISSUE THREAD

**Issue by MOONLIGHTOE** [Dev-Goliath/Bugtracker_Cataclysm#100]
Buenas tardes/noche, disculpe las molestias.
Estaba a punto de subir la reputación con Corazón Frenético y tengo un problema con el NPC que continua la cadena de misiones ya que me deja cobrar la misión, sin embargo, las siguientes misiones no me dejo usarla porque me salió un mensaje "Esta misión no esta disponible para tu raza" por lo cual creo es un bug ya que me he visto guías e incluso alguien que conoce me ha ha ayudado y hemos determinado que esta bug para Huargen y es muy probable que para goblins también (Este ultimo no lo he comprobado). El problema de esto es que no hay forma de subir la reputación de otra forma lo cual supone un problema para obtener la reputación de exaltado por lo cual no se puede adquirir el articulo “Tarro Desagradable” y tener la posibilidad de adquirir “Cerveza de Corazón Frenético” así como los demás artículos. 
Cabe recalcar que no solo es este NPC, sino, todas las misiones generadas para subir la reputación de Corazón Frenético usando de raza Huargen (Comprobado por mi pj[Mi pj es la clase Hunter raza Huargen segun videos la clase es irrelevante ya que muchos lo hacian con hunter, magos, etc. El problema lo supone la Raza]) sin embargo otros pj de clase diferente en este caso comprobado con Sacerdote de raza Draenei (Un compañero) si pueden seguir la cadena de misiones.
ID DEL NPC:28082
https://es.wowhead.com/npc=28082/alto-cham%C3%A1n-rakjak
![MENSAJE DE CLASE EN EL CHAT](https://user-images.githubusercontent.com/100053169/154824506-4b6808d3-73fd-41c0-bfa9-69d8c3d40fda.jpeg)

Mi PJ Principal es: Moonlightoe
Mi Discord: PALETERIN#9329

**Comment by Dev-Goliath** [comment]
necesitamos saber que mision sigue o en que misión te quedaste para poder ver la cadena de misiones que continua

**Comment by Dev-Goliath** [comment]
ya reportada anteriormente y corregida, disponible a partir del 10-03-2022
