### ISSUE TITLE
NPC de la mision "Hermanos en la muerte# bug

### ISSUE THREAD

**Issue by LordAkuma613** [Dev-Goliath/Bugtracker_Cataclysm#102]
El NPC con el quje se entrega a mision Hermanos en la muerte esta bug, esta en un campo antimagia y no permite interactuar con el para entregar la mision 
![2022-02-22](https://user-images.githubusercontent.com/100249759/155249012-e7d39c7a-fe61-4500-a8c4-3a969db9cf6c.png)
![2022-02-22 (1)](https://user-images.githubusercontent.com/100249759/155249058-915692bf-d73a-4db9-9fa5-fd013eea99d4.png)

**Comment by Dev-Goliath** [comment]
a él no se le entrega la mision, ya fué corregida de manera blizlike, disponible desde el 10-03-2022
![image](https://user-images.githubusercontent.com/42742610/157552615-2e2adc3c-b40c-4d7f-941c-d9f3aa09234c.png)
