### ISSUE TITLE
mision en monte hyjal bug

### ISSUE THREAD

**Issue by auralsky** [Dev-Goliath/Bugtracker_Cataclysm#103]
pj: darkwant (dk) rastam (cazador) ambos pjs atrapados con esa mision
showmaster #6046
link de la mision:  https://es.wowhead.com/quest=29197/desprevenidos
link de como se hace la mision: https://www.youtube.com/watch?v=FDjbUgEsMyE

la cadena de misiones que me llevaron a ello lo inicie con mi cazador y con este cuando abandone la misión por que estaba bug cuando quise tomarlo ya no me dejo la mision se desaparecio, y cuando lo hize con mi dk tuve que hacer todas las misiones de hyjal para llegar ahi y demostrar el bug. y vuelvo a repetir tambien que para llegar a esa mision tuve que hacer la cadena de misiones de hyjal como corresponde que me llevo horas en llegar ahi con ambos pjs, esa misión es necesaria para obtener monedas de arbol del mundo y poder entrar al portal.

![WoWScrnShot_030122_003847](https://user-images.githubusercontent.com/100650825/156108471-3289f991-a2bc-4c15-ab3c-4b7f77d24898.jpg)
![WoWScrnShot_030122_004131](https://user-images.githubusercontent.com/100650825/156108475-11c7d279-d2ad-48e8-8793-b5ae0516d15b.jpg)
![WoWScrnShot_030122_004240](https://user-images.githubusercontent.com/100650825/156108480-84b169dd-6081-4853-a757-9c0e22e0b070.jpg)
![WoWScrnShot_030122_004330](https://user-images.githubusercontent.com/100650825/156108487-2a1d7716-0413-4d57-bb7d-bdd6a4e2784f.jpg)

**Comment by Dev-Goliath** [comment]
disponible desde el 10-03-2022
