### ISSUE TITLE
Bug Logueo de Grupos de BANDA

### ISSUE THREAD

**Issue by Adravilpda** [Dev-Goliath/Bugtracker_Cataclysm#105]
Buenos días, Quiero reportar bug al momento de RELOGUEAR dentro de una Banda cualquiera, envia al jugador fuera de la Mazmorra o Banda y lo devuelve al sitio de su piedra de hogar, ademas luego de este relogueo, no se puede visualizar al grupo de Banda que pertenecía.  Debería poderse reloguear tranquilamente dentro de las Mazmorras y bandas sin dejar grupo o enviarlo afuera. Es todo ojala sea revisado porfavor.

**Comment by Dev-Goliath** [comment]
esto es así ya que al cerrar el juego o tener un jugador desconectado, deja como un fantasma o alma y por seguridad o ban loot que se daban en este tipo de mazmorras o raids, se colocó un script kick player para poder expulsar a los jugadores off.
