### ISSUE TITLE
Bug Tierras de Fuego, Adds que no se pueden ver.

### ISSUE THREAD

**Issue by Adravilpda** [Dev-Goliath/Bugtracker_Cataclysm#106]
Buenos dias. Existe un BUG en Tierras de fuego, no se pueden ver el "monton de huevos" en la zona de ALYSRAZOR para poder pegarles, solo las areas le hacen daño y los pets pueden verlo, menos los jugadores, ademas cuando se da focus al monton de huevos salen que esta fuera del alcance, tampoco se arreglan relogueando ni nada. Tambien pasa con los add "Monstruosidad llameante" que estan en la misma zona. 
Adjunto una imagen del sitio: 
![Error](https://user-images.githubusercontent.com/74122190/156934334-c74907b0-0ead-4508-9ba9-041b266cb3d5.jpg)

**Comment by Dev-Goliath** [comment]
se acaba de solucionar temporalmente con el uso de otra base de datos, pero normalmente no los ves porque necesitas cerrar y abrir wow, es un bug visual
