### ISSUE TITLE
Invasion de las tierras de fuego

### ISSUE THREAD

**Issue by anacleyta** [Dev-Goliath/Bugtracker_Cataclysm#66]
Mision  [Alas ardientes] bugg no te deja invokar en el portal no toma la zona 
![WoWScrnShot_112921_133443](https://user-images.githubusercontent.com/93929625/143910078-eb7361df-83ef-48e7-9b19-0fdf9c9533d2.jpg)
 Pj anacleyta 
https://es.wowhead.com/quest=29148/alas-ardientes

**Comment by anacleyta** [comment]
misiones  [Aliviando el dolor] y  [Los protectores de Hyjal] no se eencuentran los add en ninguna parte que tendrian que estar
![WoWScrnShot_112921_142007](https://user-images.githubusercontent.com/93929625/143914258-f84bfdc1-37e7-444e-a9d6-05b6b403a121.jpg)

![WoWScrnShot_112921_142113](https://user-images.githubusercontent.com/93929625/143914097-0d252fac-b3a5-4f66-995d-4cb2f40b2edd.jpg)
![WoWScrnShot_112921_142007](https://user-images.githubusercontent.com/93929625/143914079-1c1e4902-c3d1-4cab-833a-bc4ad0ff6418.jpg)
![WoWScrnShot_112921_142111](https://user-images.githubusercontent.com/93929625/143914090-28a237f7-96c8-4365-8ee0-02f05f6a37b0.jpg)
![WoWScrnShot_112921_142112](https://user-images.githubusercontent.com/93929625/143914092-f825c755-25d8-406f-84ab-6d6298fb757d.jpg)

https://es.wowhead.com/quest=29128/los-protectores-de-hyjal
https://es.wowhead.com/quest=29246/aliviando-el-dolor

**Comment by anacleyta** [comment]
Buenos dias como las misiones anteriores  [La bendición de la naturaleza] vas al portal y no toma como si la zona fuera invalida 
https://es.wowhead.com/quest=29162/la-bendici%C3%B3n-de-la-naturaleza
![WoWScrnShot_113021_143956](https://user-images.githubusercontent.com/93929625/144103356-dc658277-1d36-4a90-9461-094365abb153.jpg)
![WoWScrnShot_113021_144100](https://user-images.githubusercontent.com/93929625/144103370-662cbf52-c6cc-4c09-9a36-c2e2ccf51ab3.jpg)
![WoWScrnShot_113021_144120](https://user-images.githubusercontent.com/93929625/144103375-8543d62e-97fd-457a-9ee0-540ef32643b5.jpg)

**Comment by anacleyta** [comment]
Mision  [Liberando la presión] no estan los add que hay que matar para que te dropeen las escamas
https://es.wowhead.com/quest=29248/liberando-la-presi%C3%B3n
![WoWScrnShot_113021_150055](https://user-images.githubusercontent.com/93929625/144104168-e2d6714d-edcf-4650-9eea-f54396c56404.jpg)
![WoWScrnShot_113021_151205](https://user-images.githubusercontent.com/93929625/144104179-20564bd9-23f6-41ff-9736-848d5a173455.jpg)
![WoWScrnShot_113021_151225](https://user-images.githubusercontent.com/93929625/144104182-4c6a63ac-f373-46d1-895d-97473649eed1.jpg)

**Comment by Mohailaste** [comment]
tengo el mismo problema :v

![WoWScrnShot_122221_123037](https://user-images.githubusercontent.com/96385503/147117871-fa54896e-572a-4c14-b93b-6b0a2e3b9025.jpg)

**Comment by Dev-Goliath** [comment]
todas las misiones funcionan correctamente, el detalle esq no tienes reputación o estas fuera de fase porq acabo de testear mision por mision y funcionan todas.
