### ISSUE TITLE
Desaparecen los npc de la mazzmorra Cámaras de la reflexion

### ISSUE THREAD

**Issue by Kathycaptor** [Dev-Goliath/Bugtracker_Cataclysm#77]
Mientras se esta peleando con los npc llega un momento que desaparecen todos y toca volver a repetir las oleadas para derrotar a los 2 npc del inicio de la mazzmorra y no se puede terminar

**Comment by Dev-Goliath** [comment]
necesitamos saber id del npc o link del npc de wow head etc para poder solucionar este problema

**Comment by Dev-Goliath** [comment]
acabo de probar la mazmorra y funciona correctamente, obviamente tienes q ir en un grupo minimo de 5 personas para poder terminar las oleadas
