### ISSUE TITLE
Problema de visualización de miembros de hermandad.

### ISSUE THREAD

**Issue by miguel310** [Dev-Goliath/Bugtracker_Cataclysm#80]
Tengo un error con respecto a mi hermandad (Indigents Furious, nivel 14), soy el líder pero no solo me sucede a mi sino a todos los miembros y es que doy como ejemplo de que estamos 8 a 10 conectados y apenas me sale en la lista 4 personas visibles, los demás salen como si ni siquiera existieran, les dejo una captura para que observes con mas detalle. Este problema comenzó a suceder desde el día 24/01/2022, proseguimos a intentar borrar la carpeta cache y de igual manera si en el reinicio se arreglaba, pero no dio resultado. Mi usuario en discord es Omeprazol 💊#1480 en caso de que necesiten con mas detalle revisión de el problema, gracias de antemano.
![WoWScrnShot_012522_142947](https://user-images.githubusercontent.com/86680060/151218290-7e5d6436-6075-44c0-8f5c-4bce2e33f42a.jpg)

**Comment by Dev-Goliath** [comment]
cliente dañado, se puede visualizar creando una guild subiendola a nivel 13 y se ven los conectados super normal
