### ISSUE TITLE
La batalla por El bastión de Ébano

### ISSUE THREAD

**Issue by Shepardll** [Dev-Goliath/Bugtracker_Cataclysm#83]
No cuenta el boss ni los npc que se precisan matar, lo que hace que mi dk esté apaciguado o silenciado, bug al momento de tratar de realizar acciones, y entro a otro mundo utilizando el portal de la muerte, todo bug en sí, tengo que estar suicidándome para que se arregle el bug que en sí, me hace estar bloqueado de todas las acciones pvp, cambiar de presencia etc.

**Comment by Shepardll** [comment]
Mi dk se llama Shepard

**Comment by Dev-Goliath** [comment]
en ventormenta dejé un npc que te dá la misión q te falta para que te quite el apaciguado y te teletransporte a la ultima misión q te falta
