### ISSUE TITLE
Dagas Venganza y Miedo, bugueadas

### ISSUE THREAD

**Issue by Roxx0248** [Dev-Goliath/Bugtracker_Cataclysm#84]
![Screenshot_20220129-120913_Discord](https://user-images.githubusercontent.com/98659219/151670407-345bc953-4c6b-40e2-b134-95fb85d02efc.jpg)

Las dagas están bugueadas, hacen muy poco daño

**Comment by Roxx0248** [comment]
![20220129_121720](https://user-images.githubusercontent.com/98659219/151670605-efe3bf82-2b3e-4403-8c7d-7be81b30038a.jpg)
 
![20220129_121906](https://user-images.githubusercontent.com/98659219/151670607-cb98adf0-6d22-4d93-9cf7-50a182f766c5.jpg)


La primera es con las dagas y la segunda con las implacables

**Comment by Dev-Goliath** [comment]
esas dagas son parte de las legendarias por eso tienen ese daño.
