### ISSUE TITLE
mision "por todos los ciervos" BUG

### ISSUE THREAD

**Issue by SweetRevenge192** [Dev-Goliath/Bugtracker_Cataclysm#87]
mision por todos los ciervos que se toma en arboleda asesina en hyjal con el npc mylune esta bug a la hora de agarrar los ciervos que estan heridos no los cuenta y no se puede completar

**Comment by Fabiduarte** [comment]
Colocar en el reporte el nombre de su PJ principal.
Colocar en el reporte su usuario de discord (ej.: jugador#0123).
Agregar link de wowhead de el hechizo, item, logro para ser mas exactos.
Agregar una descripción del error comprensible para cualquier persona.
Agregar fotos y/o vídeos.
Agregar enlaces que validen el error (wowhead o https://cata-twinhead.twinstar.cz/)
Nota: https://cata-twinhead.twinstar.cz/ es una web que maneja las bases de datos de: Vanilla, TBC, Wotlk y Cataclysm.

**Comment by Dev-Goliath** [comment]
https://es.wowhead.com/quest=25392/por-todos-los-ciervos
el detalle de la mision es que los ciervos están muertos y deverian estar vivos caminando pero igual se pueden tomar solo 1 ciervo pero cuando intentas salir para entregar la misión estos no te siguen y se quedan parados como muestra la imagen 
![image](https://user-images.githubusercontent.com/42742610/154273318-178fd4ea-1ebe-43f6-9459-318a736d8fa8.png)
id del npc = 40000
aqui un video de referencia de como deberia realizarce 
https://www.youtube.com/watch?v=Koi79_tbv9U

**Comment by Dev-Goliath** [comment]
![image](https://user-images.githubusercontent.com/42742610/155151431-46859a25-50ca-4f6c-9794-f2c5b02ef82c.png)
algunos ciervos que están fuera o al borde si se pueden coger pero los que estan dentro de la zona no pasan como si tubieran un pared invisible q les inpide

**Comment by auralsky** [comment]
yo tambien con mis pjs tuve el mismo problema, los ciervos no te persiguen, se quedan atrapados y solo uno puede seguirte y para poder completarlo se tiene que esperar que aparesca el mismo ciervo que lograste llevar.

**Comment by Dev-Goliath** [comment]
![image](https://user-images.githubusercontent.com/42742610/157579455-61c79827-bd0d-42d9-aef1-3b9b25e8008e.png)
solucionado, disponible el dia 10-03-2022
