### ISSUE TITLE
Montura caballito de mar subyugado bug

### ISSUE THREAD

**Issue by Roxx0248** [Dev-Goliath/Bugtracker_Cataclysm#89]
Buenas esta vez quiero reportar la montura que da el npc poseidus, https://es.wowhead.com/spell=98718/caballito-de-mar-subyugado

Dice que aumenta la velocidad de nado pero al usarlo voy a la misma velocidad con la que voy sin el, gracias

**Comment by Dev-Goliath** [comment]
esa es su velocidad, fué comparado por todas las bases de datos y de todas las expansiones y corre a la misma velocidad
![image](https://user-images.githubusercontent.com/42742610/157527441-8b4207e9-25ac-4fec-a6e8-b36ac9a3e1ab.png)
