### ISSUE TITLE
REPARAR MISIONES

### ISSUE THREAD

**Issue by offwhitekj** [Dev-Goliath/Bugtracker_Cataclysm#90]
No hay misiones para subir repu de Tribu corazón frenético, a ver si lo pueden revisar y ponerlas.

**Comment by Dev-Goliath** [comment]
no sabemos que npcs las dán etc, vea la guia del repositorio para reportar porfavor, gracias.

**Comment by offwhitekj** [comment]
He revisado las misiones respecto a la repu según wow head y los npc que
deberían dar no lo hacen no sé si podría verificarlo respecto a eso.

**Comment by Dev-Goliath** [comment]
vea la guia de como reportar esto porq no se puede hacer nada asi como está el reporte

**Comment by Dev-Goliath** [comment]
![image](https://user-images.githubusercontent.com/42742610/157525655-58d25be3-66bf-451f-ad6e-95618468d2ec.png)
solucionado, disponible desde el 10-03-2022
guia de cadena de misiones 
https://es.wowhead.com/faction=1104/tribu-coraz%C3%B3n-fren%C3%A9tico#quests
