### ISSUE TITLE
Reparar misiones Hyjal 

### ISSUE THREAD

**Issue by Rulex00** [Dev-Goliath/Bugtracker_Cataclysm#92]
Las misiones para tener la "Marca del Árbol de Mundo".. Las que constan de matar elites "Alas Ardientes" - "La bendición de la naturaleza"... no se activan en la zona indicada del mapa. Arreglen eso porfavor

**Comment by Fabiduarte** [comment]
Colocar en el reporte el nombre de su PJ principal.
Colocar en el reporte su usuario de discord (ej.: jugador#0123).
Agregar link de wowhead de el hechizo, item, logro para ser mas exactos.
Agregar una descripción del error comprensible para cualquier persona.
Agregar fotos y/o vídeos.
Agregar enlaces que validen el error (wowhead o https://cata-twinhead.twinstar.cz/)
Nota: https://cata-twinhead.twinstar.cz/ es una web que maneja las bases de datos de: Vanilla, TBC, Wotlk y Cataclysm.

**Comment by Rulex00** [comment]
- Destra PJ - Rulex00#4782
- https://es.wowhead.com/quest=29148/alas-ardientes 
- El Add no sale y el item muestra que el lugar no es el correcto.
- Adjunto Foto.
![image](https://user-images.githubusercontent.com/99206966/154346053-43deabfd-0b01-444b-8735-0fa12f14b373.png)
![image](https://user-images.githubusercontent.com/99206966/154346212-84802159-d291-4674-96b4-992647ddffd7.png)

**Comment by Dev-Goliath** [comment]
![image](https://user-images.githubusercontent.com/42742610/157583272-a86cc2b4-ac33-484a-9df8-e76d6bf6af2f.png)
solucionado la mision https://es.wowhead.com/quest=29148/alas-ardientes
y la segunda tambien https://es.wowhead.com/quest=29162/la-bendici%C3%B3n-de-la-naturaleza
![image](https://user-images.githubusercontent.com/42742610/157583364-d03a3444-a4c9-48f3-9f46-f0e8f0e4e45e.png)
disponibles el 10 - 03 - 2022
