### ISSUE TITLE
reparar mision joyeria

### ISSUE THREAD

**Issue by alrixas** [Dev-Goliath/Bugtracker_Cataclysm#93]
Buenas, la misión de hacer piedras intemporales para sacar muestra de ijoyero ilustre esta bug, ya tengo las que me pide pero no me deja completarla. 

Para que la revisen

**Comment by Dev-Goliath** [comment]
estas misiones son individuales, si estas en un grupo  o la hiciste dentro de un grupo o banda, asi las hayas pulido, tienes q pulirlas estando completamente solo
