### ISSUE TITLE
Banda Anh Qiraj (resurrecion bug) #95

### ISSUE THREAD

**Issue by shavi01** [Dev-Goliath/Bugtracker_Cataclysm#95]
Buenos días, tarde o noches.
Por favor su gentil ayuda la banda de Anh Qiraj esta bug para revivir mi personaje es enviado a las afueras de la banda y sale el error tu cuerpo no esta en esta instancia y también no hay un ángel de resurrección en la zona .
Esperando su ayuda mi war se quedo sin poder revivir ni salir de esa zona.
 De ante mano agradeciendo suayuda  muchas gracias

Territorio: En disputa (expacion classic wow )
Tipo de instancia: Banda
Número de jugadores: 40
ID de Zona: 3428 

psd. mi primer post asi XD

**Comment by rampague** [comment]
Colocar en el reporte el nombre de su PJ principal.
Colocar en el reporte su usuario de discord (ej.: jugador#0123).
Agregar link de wowhead de el hechizo, item, logro para ser mas exactos.
Agregar una descripción del error comprensible para cualquier persona.
Agregar fotos y/o vídeos.
Agregar enlaces que validen el error (wowhead o https://cata-twinhead.twinstar.cz/)
Nota: https://cata-twinhead.twinstar.cz/ es una web que maneja las bases de datos de: Vanilla, TBC, Wotlk y Cataclysm.

**Comment by Fabiduarte** [comment]
Colocar en el reporte el nombre de su PJ principal.
Colocar en el reporte su usuario de discord (ej.: jugador#0123).
Agregar link de wowhead de el hechizo, item, logro para ser mas exactos.
Agregar una descripción del error comprensible para cualquier persona.
Agregar fotos y/o vídeos.
Agregar enlaces que validen el error (wowhead o https://cata-twinhead.twinstar.cz/)
Nota: https://cata-twinhead.twinstar.cz/ es una web que maneja las bases de datos de: Vanilla, TBC, Wotlk y Cataclysm.

**Comment by Dev-Goliath** [comment]
![image](https://user-images.githubusercontent.com/42742610/157529101-56e1d910-cd0b-4e8d-af7c-554d382b418b.png)
el angel si se encuentra disponible para resurección
