### ISSUE TITLE
MISIONES NO-HABIDAS

### ISSUE THREAD

**Issue by offwhitekj** [Dev-Goliath/Bugtracker_Cataclysm#96]
Buen dia gms, he tratado de subir la reputación TRIBU CORAZÓN FRENÉTICO pero de acuerdo a guías en google y wow head de quienes te entregan las misiones y donde entregarlas en el juego no me las dan. Podría revisar sobre estos NPCs que no estan dando las misiones para dicha reputación ya voy mas de 2 semanas y no encuentro.

**Comment by rampague** [comment]
Colocar en el reporte el nombre de su PJ principal.
Colocar en el reporte su usuario de discord (ej.: jugador#0123).
Agregar link de wowhead de el hechizo, item, logro para ser mas exactos.
Agregar una descripción del error comprensible para cualquier persona.
Agregar fotos y/o vídeos.
Agregar enlaces que validen el error (wowhead o https://cata-twinhead.twinstar.cz/)
Nota: https://cata-twinhead.twinstar.cz/ es una web que maneja las bases de datos de: Vanilla, TBC, Wotlk y Cataclysm.

**Comment by Fabiduarte** [comment]
Colocar en el reporte el nombre de su PJ principal.
Colocar en el reporte su usuario de discord (ej.: jugador#0123).
Agregar link de wowhead de el hechizo, item, logro para ser mas exactos.
Agregar una descripción del error comprensible para cualquier persona.
Agregar fotos y/o vídeos.
Agregar enlaces que validen el error (wowhead o https://cata-twinhead.twinstar.cz/)
Nota: https://cata-twinhead.twinstar.cz/ es una web que maneja las bases de datos de: Vanilla, TBC, Wotlk y Cataclysm.

**Comment by Dev-Goliath** [comment]
reportado anteriormente ya solucionado y disponible desde el 10-03-2022
