### ISSUE TITLE
Los protectores de Hyjal 

### ISSUE THREAD

**Issue by Rulex00** [Dev-Goliath/Bugtracker_Cataclysm#98]
- Destra PJ - Rulex00#4782 
- https://es.wowhead.com/quest=29128/los-protectores-de-hyjal
- Indica el destino donde se debe matar 6 adds pero no hay ninguno. 
- Foto. 
![image](https://user-images.githubusercontent.com/99206966/154347017-514e0531-1cae-4176-a464-246bcfe5812f.png)
![image](https://user-images.githubusercontent.com/99206966/154347135-1a58da8f-0b22-4f71-8279-9cf2bf40aaad.png)

- Video de muestra sacado de Youtube.
https://www.youtube.com/watch?v=hcqyzf7EaUM

**Comment by MOONLIGHTOE** [comment]
No se si haz ido actualmente (Yo hoy termine todas las misiones de hyjal y subí repu a exaltado)

**Comment by auralsky** [comment]
esa misión yo logre pasarla de forma normal los npc que tienes que matar estan ahi disponibles que raro que el tuyo no funcione.

**Comment by Dev-Goliath** [comment]
solucionado y disponible el dia 10-03-2022
