### ISSUE TITLE
Bug en desolace.

### ISSUE THREAD

**Issue by Rulex00** [Dev-Goliath/Bugtracker_Cataclysm#99]
Destra - Rulex00#4782

Tengo problemas en ingresar con un pj.. desde que entre la zona de desolace.

![image](https://user-images.githubusercontent.com/99206966/154497337-f3a92212-c00a-4682-8716-f024ca4214f0.png)

![image](https://user-images.githubusercontent.com/99206966/154497988-f5328733-87cc-45e9-8ddb-2c0124859cf4.png)

**Comment by Dev-Goliath** [comment]
descargar los drivers actuales para su ordenador y eliminar el juego y volver a jugar con el runplay mostrado aqui 
cliente minimal en español 4.3.4 6mb por mega https://mega.nz/file/0b5UCDjR#k_wU3-M9_GpzbvFJyqFehP-Mnxq6DZkg_NuHZmofKZw
